In [171]:
import numpy as np
from sympy import *
import re
import pandas as pd

In [219]:
#1.  Write a Python program to compute the eigenvalues and right eigenvectors of a given square array.
## Example Matrix
a = np.array([[7,3],[3,-1]])
## The Easy Way 
values, vectors = np.linalg.eig(a)
print(values)
print(vectors)

## Ax = lx
## Assign l as eigenvalue lambda
y = Symbol('y')
## Multiply identify matrix by y to get yI
yI = y*eye(2)
## Subtract yI from a 
a2 = a - yI
## Calculate determinant
a3 = det(a2)
## Solve polynomial to get Eigenvalues 8 and -2 for this example
a4 = roots(a3)
a5 = a4.items()
a6 = pd.DataFrame.from_dict(a5)  #Convert dictionary to dataframe
a7 = array(a6.iloc[:, 0])        #Retrieve 1st column of dataframe as an array
print("Eigenvalues: ",a7)
eval1 = a7[0]
eval2 = a7[1]
evecM1 = a - (evalue1 * eye(2))
evec1 = evecM1.rref()
evecM2 = a - (evalue2 * eye(2))
evec2 = evecM2.rref()
print(evec1, evec2)  ## Can't seem to figure out how to get eigenvectors using rref

[ 8. -2.]
[[ 0.9486833  -0.31622777]
 [ 0.31622777  0.9486833 ]]
Eigenvalues:  [8 -2]
(Matrix([
[1, -3],
[0,  0]]), (0,)) (Matrix([
[1, 1/3],
[0,   0]]), (0,))


In [152]:
#2.  Write a Python program to compute the factor of a given array by Singular Value Decomposition
## Example Matrix
from scipy.linalg import svd
a = array([[7,3],[3,-1]])

U,s,V = svd(a)
print(U)
print(s)
print(V)

[[-0.9486833  -0.31622777]
 [-0.31622777  0.9486833 ]]
[8. 2.]
[[-0.9486833  -0.31622777]
 [ 0.31622777 -0.9486833 ]]


In [211]:
#3.  Write a Python program to compute the determinant of an array.
## Example Matrix
a = array([[7,3],[3,-1]])
print(linalg.det(a))
## Determinant is the product of all the eigenvalues of the matrix
values, vectors = np.linalg.eig(a)
print(values[0]*values[1])
## or for 2x2 multiply diagonals and subtract
print(a[0,0]*a[1,1]-a[0,1]*a[1,0])

-15.999999999999998
-16.0
-16
